apiVersion: v1
kind: Pod
metadata:
  labels:
    app: redis
  name: redis
  namespace: demo
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  containers:
  - image: gcr.io/google-samples/microservices-demo/cartservice:v0.3.6
    name: server
    env:
    - name: REDIS_ADDR
      value: redis-cart:6379
    ports:
      - containerPort: 7070
    livenessProbe:
      exec:
        command:
        - /bin/grpc_health_probe
        - -addr=:7070
        - -rpc-timeout=5s
      initialDelaySeconds: 15
      periodSeconds: 10
    readinessProbe:
      exec:
        command:
        - /bin/grpc_health_probe
        - -addr=:7070
        - -rpc-timeout=5s
      initialDelaySeconds: 15
    resources:
      limits:
        cpu: 300m
        memory: 128Mi
      requests:
        cpu: 200m
        memory: 64Mi

    securityContext:
      runAsNonRoot: true 
      readOnlyRootFilesystem: false  
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - all